// This file has been generated by zoltan (https://github.com/jac3km4/zoltan)

#define ZOLTAN_STRINGISE(N) #N
#define ZOLTAN_EXPAND_THEN_STRINGISE(N) ZOLTAN_STRINGISE(N)
#define __LINE_STR__ ZOLTAN_EXPAND_THEN_STRINGISE(__LINE__)

#ifndef LoadResRefAddr_Addr
#define LoadResRefAddr_Addr 0x4A1B90
#endif
#ifndef UpdateNavPath_Addr
#define UpdateNavPath_Addr 0x368200
#endif
